### PR TITLE
Support for Symfony 4

### PR DESCRIPTION
**Pull request by Nyholm**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by davedevelopment** [comment]
Thanks1

**Comment by rainbow-alex** [comment]
@davedevelopment can you release this so I don't have to require dev-master?

**Comment by rainbow-alex** [comment]
@davedevelopment sorry to ask again, can you please tag this as a release?

**Comment by davedevelopment** [comment]
Sorry I ignored you the first time, just tagged v1.5.0

**Pull request merged**
